name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      run: cmake -B build -S source

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      working-directory: build
      run: ctest --build-config Release
